-- MySQL Script generated by MySQL Workbench
-- 10/22/16 15:45:35
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bd_tv
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_tv
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_tv` DEFAULT CHARACTER SET utf8 ;
USE `bd_tv` ;

-- -----------------------------------------------------
-- Table `bd_tv`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_tv`.`Endereco` (
  `idEndereco` INT NOT NULL,
  `rua` VARCHAR(45) NULL,
  `numero` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `cep` INT NULL,
  PRIMARY KEY (`idEndereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_tv`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_tv`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `nome` VARCHAR(255) NULL,
  `cpf` INT NULL,
  `genero` VARCHAR(45) NULL,
  `dtNascimento` DATETIME NULL,
  `telefone` INT NULL,
  `matricula` INT NULL,
  `login` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `Endereco_idEndereco` INT NOT NULL,
  `idTitular` INT NOT NULL,
  PRIMARY KEY (`idUsuario`, `Endereco_idEndereco`, `idTitular`),
  UNIQUE INDEX `idUsuario_UNIQUE` (`idUsuario` ASC),
  INDEX `fk_Usuario_Endereco_idx` (`Endereco_idEndereco` ASC),
  INDEX `fk_Usuario_Usuario1_idx` (`idTitular` ASC),
  CONSTRAINT `fk_Usuario_Endereco`
    FOREIGN KEY (`Endereco_idEndereco`)
    REFERENCES `bd_tv`.`Endereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Usuario1`
    FOREIGN KEY (`idTitular`)
    REFERENCES `bd_tv`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_tv`.`Plano`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_tv`.`Plano` (
  `idPlano` INT NOT NULL,
  `titulo` VARCHAR(255) NULL,
  PRIMARY KEY (`idPlano`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_tv`.`Contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_tv`.`Contrato` (
  `idContrato` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Plano_idPlano` INT NOT NULL,
  `codigoContrato` INT NULL,
  `situacao` VARCHAR(45) NULL,
  `dtInicial` VARCHAR(45) NULL,
  `dtEncerramento` VARCHAR(45) NULL,
  PRIMARY KEY (`idContrato`, `Usuario_idUsuario`, `Plano_idPlano`),
  INDEX `fk_Contrato_Usuario1_idx` (`Usuario_idUsuario` ASC),
  INDEX `fk_Contrato_Plano1_idx` (`Plano_idPlano` ASC),
  CONSTRAINT `fk_Contrato_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `bd_tv`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contrato_Plano1`
    FOREIGN KEY (`Plano_idPlano`)
    REFERENCES `bd_tv`.`Plano` (`idPlano`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_tv`.`Canal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_tv`.`Canal` (
  `idCanal` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `numero` VARCHAR(45) NULL,
  PRIMARY KEY (`idCanal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_tv`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_tv`.`Categoria` (
  `idCategoria` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_tv`.`Canal_Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_tv`.`Canal_Categoria` (
  `idCanal_Categoria` INT NOT NULL,
  `Canal_idCanal` INT NOT NULL,
  `Categoria_idCategoria` INT NOT NULL,
  PRIMARY KEY (`idCanal_Categoria`, `Canal_idCanal`, `Categoria_idCategoria`),
  INDEX `fk_Canal_Categoria_Canal1_idx` (`Canal_idCanal` ASC),
  INDEX `fk_Canal_Categoria_Categoria1_idx` (`Categoria_idCategoria` ASC),
  CONSTRAINT `fk_Canal_Categoria_Canal1`
    FOREIGN KEY (`Canal_idCanal`)
    REFERENCES `bd_tv`.`Canal` (`idCanal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Canal_Categoria_Categoria1`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `bd_tv`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_tv`.`Plano_Canal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_tv`.`Plano_Canal` (
  `idPlano_Canal` INT NOT NULL,
  `Plano_idPlano` INT NOT NULL,
  `Canal_idCanal` INT NOT NULL,
  `dtInicio` VARCHAR(45) NULL,
  `Plano_Canalcol` VARCHAR(45) NULL,
  PRIMARY KEY (`idPlano_Canal`, `Plano_idPlano`, `Canal_idCanal`),
  INDEX `fk_Plano_Canal_Plano1_idx` (`Plano_idPlano` ASC),
  INDEX `fk_Plano_Canal_Canal1_idx` (`Canal_idCanal` ASC),
  CONSTRAINT `fk_Plano_Canal_Plano1`
    FOREIGN KEY (`Plano_idPlano`)
    REFERENCES `bd_tv`.`Plano` (`idPlano`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Plano_Canal_Canal1`
    FOREIGN KEY (`Canal_idCanal`)
    REFERENCES `bd_tv`.`Canal` (`idCanal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_tv`.`Programa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_tv`.`Programa` (
  `idPrograma` INT NOT NULL,
  `titulo` VARCHAR(255) NULL,
  `data` DATE NULL,
  `classificacao` VARCHAR(45) NULL,
  PRIMARY KEY (`idPrograma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_tv`.`Grade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_tv`.`Grade` (
  `idGrade` INT NOT NULL,
  `Canal_idCanal` INT NOT NULL,
  `Programa_idPrograma` INT NOT NULL,
  `horarioInicial` VARCHAR(45) NULL,
  `horarioFinal` VARCHAR(45) NULL,
  PRIMARY KEY (`idGrade`, `Canal_idCanal`, `Programa_idPrograma`),
  INDEX `fk_Grade_Programa1_idx` (`Programa_idPrograma` ASC),
  INDEX `fk_Grade_Canal1_idx` (`Canal_idCanal` ASC),
  CONSTRAINT `fk_Grade_Programa1`
    FOREIGN KEY (`Programa_idPrograma`)
    REFERENCES `bd_tv`.`Programa` (`idPrograma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Grade_Canal1`
    FOREIGN KEY (`Canal_idCanal`)
    REFERENCES `bd_tv`.`Canal` (`idCanal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
